### PR TITLE
Fix for npm run start command error

### PR DESCRIPTION
**Pull request by paintedbicycle**
When running npm run start, it calls an npm script that then calls
yarn. However, this is supposed to be an npm-only command. This commit
changes the documentation to directly run the patternlab:serve command
instead

### CODE REVIEW

**Comment by paintedbicycle** [comment]
Let me know if you'd prefer to change the script command in the package.json file instead of solving it this way. 

Also, I'm not sure how to complete the CLA signing. Perhaps I filled it out correctly.

**Comment by mbulfair** [comment]
@paintedbicycle your email address that you used to make the commit needs to be apart of your github account for the CLA to work. https://github.com/settings/emails so if they do not match, you have to just add any alternate ones.

**Comment by paintedbicycle** [comment]
Thanks, yes I read that, but one on my account needs to match where? I have a public email in that spot on my account...it needs to correspond to this commit? Where is the "commit email"? Sorry for the hassle

**Comment by mbulfair** [comment]
When you made the commit, was it with `paul@paintedbicycle.com`  or another? Both emails just need to be in your github.com account for it to sign properly.

**Comment by paintedbicycle** [comment]
There was no public email associated with my account at that time, if that's what you mean. Otherwise I don't know how to check this. When I made this commit, I just forked, changed and committed all with this account...no idea about an email association.

**Comment by mbulfair** [comment]
If you type `git log` under author, that email address, must be in your github.com account under emails. That's what the CLA is comparing against. It's saying that the email of the author doesn't exist in a github.com account.

**Comment by paintedbicycle** [comment]
OK, yes it was empty (using my local computer's username), so it doesn't match my email. I'll just close this PR

**Comment by mbulfair** [comment]
ok, I'll make the change for you if you'd like @paintedbicycle

**Comment by paintedbicycle** [comment]
Sure, if you agree with it, feel free. Thanks

**Comment by JohnRiv** [comment]
Hi @paintedbicycle, thanks for your contribution! I want to make sure any additional PRs you'd like to make can be merged in successfully, so here are a couple git tips around emails:

1. To change the email associated with your last commit, run:
```
git commit --amend --author "NAME_GOES_HERE <EMAIL@GOES.HERE>"
```

2. You'll want to set your email address either globally on your computer (recommended), or remember to set it before making any edits to a repo by following the instructions here: https://help.github.com/articles/setting-your-commit-email-address-in-git/

Then as Matt mentioned, as long as the email associated with your git commit is also associated with your GitHub account, the CLA tool will recognize you've already signed it

**Comment by paintedbicycle** [comment]
Ah, ok, thank you for that. I have fixed my commit on my repo and set my default address locally going forward. Is there a way to update this PR with the new commit?

**Comment by JohnRiv** [comment]
You'll have to force-push your update to repo:
```
git push origin master --force
```
and then in theory that should automatically update this PR... I'll reopen it so we can see if that works

**Comment by paintedbicycle** [comment]
Done. Looks like it all worked. 

Thank you for teaching me to git on the command line. ::embarrassed-emoji

**Comment by JohnRiv** [comment]
Awesome! Happy to help @paintedbicycle 😄

**Pull request merged**
